package sqlite

import ("context"; "database/sql"; "fmt")
type Repositories struct { SystemConfigs systemConfigRepo; SystemUsers systemUserRepo; SonarrRules sonarrRuleRepo; RadarrRules radarrRuleRepo; SonarrTitles sonarrTitleRepo; RadarrTitles radarrTitleRepo; TMDBTitles tmdbTitleRepo }
func (s *Store) Repositories() Repositories { return Repositories{systemConfigRepo{s.db},systemUserRepo{s.db},sonarrRuleRepo{s.db},radarrRuleRepo{s.db},sonarrTitleRepo{s.db},radarrTitleRepo{db:s.db,store:s},tmdbTitleRepo{s.db}} }
type systemConfigRepo struct{ db *sql.DB }; type systemUserRepo struct{ db *sql.DB }; type sonarrRuleRepo struct{ db *sql.DB }; type radarrRuleRepo struct{ db *sql.DB }; type sonarrTitleRepo struct{ db *sql.DB }; type radarrTitleRepo struct{ db *sql.DB; store *Store }; type tmdbTitleRepo struct{ db *sql.DB }
func (r systemConfigRepo) Upsert(c context.Context,v SystemConfig) error { _,e:=r.db.ExecContext(c,`INSERT INTO system_config(id,"key",value,valid_status,create_time,update_time) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET "key"=excluded."key",value=excluded.value,valid_status=excluded.valid_status,create_time=excluded.create_time,update_time=excluded.update_time`,v.ID,v.Key,v.Value,v.ValidStatus,v.CreateTime,v.UpdateTime); return wrap("upsert system config",e) }
func (r systemConfigRepo) Get(c context.Context,id SystemConfigID)(v SystemConfig,e error){ e=r.db.QueryRowContext(c,`SELECT id,"key",value,valid_status,create_time,update_time FROM system_config WHERE id=?`,id).Scan(&v.ID,&v.Key,&v.Value,&v.ValidStatus,&v.CreateTime,&v.UpdateTime); return v,wrap("get system config",e) }
func (r systemUserRepo) Upsert(c context.Context,v SystemUser) error { _,e:=r.db.ExecContext(c,`INSERT INTO system_user(id,username,password,role,valid_status,create_time,update_time) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,password=excluded.password,role=excluded.role,valid_status=excluded.valid_status,create_time=excluded.create_time,update_time=excluded.update_time`,v.ID,v.Username,v.Password,v.Role,v.ValidStatus,v.CreateTime,v.UpdateTime); return wrap("upsert system user",e) }
func (r systemUserRepo) Get(c context.Context,id SystemUserID)(v SystemUser,e error){e=r.db.QueryRowContext(c,`SELECT id,username,password,role,valid_status,create_time,update_time FROM system_user WHERE id=?`,id).Scan(&v.ID,&v.Username,&v.Password,&v.Role,&v.ValidStatus,&v.CreateTime,&v.UpdateTime);return v,wrap("get system user",e)}
func wrap(op string,e error)error{if e!=nil{return fmt.Errorf("%s: %w",op,e)};return nil}
